spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/area} # TODO : .env
    username: ${SPRING_DATASOURCE_USERNAME:postgres} # TODO : .env
    password: ${SPRING_DATASOURCE_PASSWORD:postgres} # TODO : .env
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost} # TODO : .env
      port: ${SPRING_REDIS_PORT:6379} # TODO : .env

server:
  port: ${SERVER_PORT:8080} # TODO : .env

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
