do_token               = ""
ssh_key_id             = ""
private_key_path       = ""
domain_name            = ""
email_mx_server        = ""
email_spf_record       = ""
email_dkim_public_key  = ""
email_dmarc_policy     = ""