# Generated by Django 4.2.7 on 2025-09-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_oauth_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oauthaccount',
            name='unique_provider_user',
        ),
        migrations.AlterUniqueTogether(
            name='oauthaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
